name: package

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: "ref branch for this workflow"
        default: "master"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  package-macos-arm64:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
    - name: Install Prerequisites
      run: bin/install_prerequisites_macos.sh
    - name: Install python3 venv
      run: |
        bin/install_python3_venv.sh
        export PATH=/tmp/hurl-python3-venv/bin:$PATH
        which python3
        python3 --version
        pip --version
    - name: Install Rust
      run: |
        bin/install_rust.sh
        rustup target add aarch64-apple-darwin
    - name: Environment
      run: bin/environment.sh
    - name: Build
      run: |
        sed -i '' 's/cargo build/cargo build --target=aarch64-apple-darwin/g' bin/release/release.sh
        export PKG_CONFIG_ALLOW_CROSS=1
        #export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
        #export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
        #export CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
        bin/release/release.sh
        echo "PATH=:${PWD}/target/release:$PATH" >> "${GITHUB_ENV}"
    - name: Get version
      run: |
        VERSION=$(bin/release/get_version.sh)
        echo "VERSION=${VERSION}" | tee -a "${GITHUB_ENV}"
    - name: Create generic macos package
      run: |
        bin/release/man.sh
        bin/release/create_tarball.sh
    - name: Install package
      run: |
        bin/release/install_generic_macos_package.sh
        echo "PATH=/tmp/hurl-generic-macos:$PATH" >> "${GITHUB_ENV}"
    - name: Test integ
      run: |
        bin/test/test_prerequisites.sh
        bin/test/test_integ.sh
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-macos-arm64-artifacts
        path: target/upload/*
